# Generated by Django 4.1.6 on 2023-03-12 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorityname', models.CharField(max_length=100)),
                ('official', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('proof', models.ImageField(upload_to='')),
                ('regdate', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('regdate', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.BigIntegerField(null=True)),
                ('aid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartapp.authority')),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartapp.public')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartapp.public')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=500, null=True)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('proof', models.ImageField(null=True, upload_to='')),
                ('status', models.CharField(max_length=100, null=True)),
                ('rply', models.CharField(max_length=500, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('lon', models.CharField(max_length=50, null=True)),
                ('lat', models.CharField(max_length=50, null=True)),
                ('authority', models.CharField(max_length=50, null=True)),
                ('aldt', models.DateField(auto_now_add=True, null=True)),
                ('duedt', models.DateField(null=True)),
                ('aid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartapp.authority')),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartapp.public')),
            ],
        ),
        migrations.CreateModel(
            name='Bestauthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartapp.authority')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartapp.authority')),
                ('compid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartapp.complaint')),
            ],
        ),
    ]
