# Generated by Django 4.1.6 on 2023-04-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='dist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authority',
            name='offdesig',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
