# Generated by Django 4.1.6 on 2023-04-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0002_authority_dist_authority_offdesig'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='aanum',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
