# Generated by Django 4.1.6 on 2023-04-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0003_public_aanum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
