# Generated by Django 4.1.6 on 2023-04-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0004_alter_public_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='addinfo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
