# Generated by Django 4.1.6 on 2023-04-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0005_complaint_addinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bestauthority',
        ),
    ]
